### PR TITLE
CP-381 Release karma-jspm 1.1.4

### PR DESCRIPTION
**Pull request by jayudey-wf**
PRs contained in this release:

https://github.com/Workiva/karma-jspm/pull/35

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/karma-jspm/compare/1.1.3...Release_1.1.4

How To +10/QA
-------------

```bash
# skip the following steps if you've already initialized the project
git clone git@github.com:Workiva/karma-jspm.git
cd karma-jspm

# do not skip these!
git fetch && git checkout Release_1.1.4
Run unit tests
```

### CODE REVIEW

**Comment by rmconsole-wf** [comment]
## General Information
Ticket(s): <a href='https://jira.webfilings.com/browse/CP-381'>CP-381</a> 
Code Review: https://github.com/Workiva/karma-jspm/pull/36
CI: 
Automation Run: 
## RM Checklist
- [ ] Last Commit Reviewed
- [x] Unit Tests Added
- [x] Security Review Completed if Applicable:  (N/A)

## Additional Information

		When this pull is merged I will use the following information:
		Version: karma-jspm 1.1.4
		Release Ticket: CP-381

		This pull is considered the release of karma-jspm 1.1.4. 
		This repo will be tagged, release notes will be created, and communication will go out.

***
*Last updated on Monday, February 02 01:35 PM CST*

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
