### PR TITLE
CP-1771 Release karma-jspm 2.2.0

### PR DESCRIPTION
**Pull request by charliekump-wf**
PRs contained in this release:

https://github.com/Workiva/karma-jspm/pull/131

https://github.com/Workiva/karma-jspm/pull/149

https://github.com/Workiva/karma-jspm/pull/154

https://github.com/Workiva/karma-jspm/pull/101

https://github.com/Workiva/karma-jspm/pull/167

https://github.com/Workiva/karma-jspm/pull/156

=======

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/karma-jspm/compare/2.1.1...Release_2.2.0

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
QA +1

- [x] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
