### PR TITLE
Fixes #158 - add options for dev/node config files

### LINKED ISSUE #158: Two more possible config files (jspm 0.17-beta.17)
The latest jspm version (0.17-beta.17, at the time of writing) adds support for more config files:

* a separate config file for the devDependencies (`jspm.dev.js` for example)
* a separate config file for Node environments

This brings all the config files to:

* config: `jspm.config.js`
* browser: `jspm.browser.js`
* dev: `jspm.dev.js`
* node: `jspm.node.js` (not sure about the default name here, haven't used it)

This would need to extra karma-jspm options, next to `config` and `browser`: `dev` and `node`.

If I can find the time, I should be able to make a PR for this.

### PR DESCRIPTION
**Pull request by sergei-maertens**
This adds two more config file options that are available in jspm 0.17 beta

### CODE REVIEW

**Comment by evanweible-wf** [comment]
+1 Thanks @sergei-maertens!

@trentgrover-wf @dustinlessard-wf

**Comment by sergei-maertens** [comment]
Fwiw, in the long term the suggested approach of #156 might be more viable, either would be fine for me.

**Comment by trentgrover-wf** [comment]
I'd vote to go with #156 instead since it's the more generalized solution

thoughts @maxwellpeterson-wf @evanweible-wf ?

**Comment by sergei-maertens** [comment]
I only saw it after I submitted the PR ofcourse, so +1 from me on #156 as
well

**Comment by evanweible-wf** [comment]
That works for me, I'll go ahead and close this.

**Pull request closed without merging**
