### PR TITLE
CP-1006 Strip extension config

### PR DESCRIPTION
**Pull request by valotas**
Made the module name computation configurable.

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
You'll need to pass the config onto the client in `init.js` similar to here: https://github.com/Workiva/karma-jspm/blob/master/src/init.js#L78

**Comment by valotas** [comment]
Done.

Why don't you just copy the whole object? It is very easy to forget to do that otherwise.

**Comment by trentgrover-wf** [comment]
+1
@maxwellpeterson-wf @evanweible-wf

**Comment by maxwellpeterson-wf** [comment]
@valotas good point, we should do that. Want to submit a patch? :)

+1
@jayudey-wf ready for merge

**Comment by valotas** [comment]
Sure. I'll have a look at it within the week

**Comment by evanweible-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction (gathered from discussion with Max Peterson)
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - installed in another project that consumes karma-jspm, verified that tasks were still working as expected
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into mast

**Pull request merged**
