### PR TITLE
CP-344 Karma-jspm IE8 fix

### PR DESCRIPTION
**Pull request by trentgrover-wf**
## Problem
- can't use karma-jspm to test in IE8

## Solution
- `System['import']` instead of `System.import`
- `['catch']` instead of `.catch`

## Testing
- unit tests pass

@maxwellpeterson-wf 
@evanweible-wf 
@charliekump-wf 
@jayudey-wf

### CODE REVIEW

**Comment by computmaxer** [comment]
+1

**Comment by ekweible** [comment]
+1

**Comment by trentgrover-wf** [comment]
@charliekump-wf @jayudey-wf ready for merge and patch fix tag (need to pull this into wGulp)

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - unit tests pass
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

@charliekump-wf  ready for patch release

**Pull request merged**
