### PR TITLE
CP-592 Release karma-jspm 2.0.0-beta.1

### PR DESCRIPTION
**Pull request by jayudey-wf**
PRs contained in this release:

https://github.com/Workiva/karma-jspm/pull/61
https://github.com/Workiva/karma-jspm/pull/62

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/karma-jspm/compare/1.1.5...Release_2.0.0-beta.1

### CODE REVIEW

**Comment by evanweible-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Pull request merged**
