### PR TITLE
CP-2039 fix(init): issue #162

### PR DESCRIPTION
**Pull request by m-a-r-c-e-l-i-n-o**
See issue #162.

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by evanweible-wf** [comment]
+1 

@maxwellpeterson-wf @trentgrover-wf

**Comment by computmaxer** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+10
- test pass and works as expected

**Pull request merged**
