### PR TITLE
CP-734 Update README to mention of plugin configuration

### PR DESCRIPTION
**Pull request by timkindberg**
related to #46

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1
@trentgrover-wf @evanweible-wf

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
@charliekump-wf ready for merge

**Comment by charliekump-wf** [comment]
QA +1 

Documentation only. Merging into master.

**Pull request merged**
