### PR TITLE
CP-1447 Support for JSPM 0.17 Beta

### PR DESCRIPTION
**Pull request by rafiwardak2003**
Added an option to pass a jspm.browser.js file needed for JSPM 0.17 Beta.

### CODE REVIEW

**Comment by SerkanSipahi** [comment]
Who will merge this into master ?

**Comment by rafiwardak2003** [comment]
Not sure... but if anyone is trying out JSPM beta 0.17, they might need this with it.

**Comment by maxwellpeterson-wf** [comment]
+1 @trentgrover-wf @evanweible-wf

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for merge

**Comment by evanweible-wf** [comment]
+1

**Comment by SerkanSipahi** [comment]
+1 sounds good

**Comment by MSakamaki** [comment]
+1

**Comment by rolandjitsu** [comment]
Is anyone actually going to merge this and release?

**Comment by evanweible-wf** [comment]
@jayudey-wf

**Comment by maxwellpeterson-wf** [comment]
+10
- confirmed that adding a `browser` option to `jspm` in the config causes karma to load the browser file.

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Testing instruction (derived by Max)
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - performed and documented by Max
- [ ] Unit test created/updated
- [ ] All unit tests pass 

Merging into master.

**Comment by SerkanSipahi** [comment]
yeaaah, its merged :+1:

**Comment by SerkanSipahi** [comment]
@jayudey-wf @maxwellpeterson-wf  @evanweible-wf @trentgrover-wf Thank you guys. I have a complex project that was based on karma-jspm 2.0.3. The change to 2.1.0 was without problem :)

**Pull request merged**
