### PR TITLE
CP-380 properly declare variables as local, not as globals

### PR DESCRIPTION
**Pull request by capaj**
that's like the first rule of javascript

dafuq

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
@jayudey-wf ready for merge and patch tag

**Comment by jayudey-wf** [comment]
QA +1, functional changes - just a code bestpractice

Merging

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Comment by rmconsole-wf** [comment]
## General Information
Ticket(s): <a href='https://jira.webfilings.com/browse/CP-380'>CP-380</a> 
Code Review: https://github.com/Workiva/karma-jspm/pull/35
CI: 
Automation Run: 
- [x] Last Commit Reviewed
- [x] Security Review Completed if Applicable:  (N/A)

***
*Last updated on Monday, February 02 01:28 PM CST*

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Pull request merged**
