### PR TITLE
CP-544 Release karma-jspm 1.1.5

### PR DESCRIPTION
**Pull request by jayudey-wf**
PRs contained in this release:

https://github.com/Workiva/karma-jspm/pull/48
https://github.com/Workiva/karma-jspm/pull/50
https://github.com/Workiva/karma-jspm/pull/47

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/karma-jspm/compare/1.1.4...Release_1.1.5

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by charliekump-wf** [comment]
QA +1

- [x] Dev +1 only needed for release.

Ready for merge and tag.

**Comment by zewa666** [comment]
Just wanted to highlight that the npm registry hasn't been updated. If you could do that that would be awesome

**Comment by computmaxer** [comment]
Done!

**Comment by maxwellpeterson-wf** [comment]
Done!

**Pull request merged**
