### PR TITLE
CP-767 Save CPU cycles by not watching jspm_packages directory for changes.

### PR DESCRIPTION
**Pull request by ggranum**
One could also set usePolling to false and pray.

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
Thanks for the contribution! You'll need to fix this line of the unit test: https://github.com/Workiva/karma-jspm/blob/master/test/testInit.spec.js#L58 in order to get a passing build.

**Comment by trentgrover-wf** [comment]
@maxwellpeterson-wf looks like this PR was abandoned, so if it's useful, might as well finish it off yourself

**Comment by ggranum** [comment]
@maxwellpeterson-wf I'm a bit embarrassed that I didn't run the tests on the unit-testing addon :~) Thanks for pointing out the exact line number.

@trentgrover-wf Thanks for comment. Crazy house move pushed this and a dozen other things off the end of the queue. I needed the reminder, sadly.

**Comment by trentgrover-wf** [comment]
+1

**Comment by gavinaiken** [comment]
I was just about to contribute a PR with the exact same purpose as this, glad someone else got there first! :+1: How often do you guys do releases i.e. when is this likely to be out on npm?

**Comment by maxwellpeterson-wf** [comment]
+1
@jayudey-wf ready for merge
@gavinaiken I can get this in a patch release once it is merged and goes through our release process. Likely will be on npm tomorrow morning.

**Comment by jayudey-wf** [comment]
go @rmconsole-wf

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - passing CI
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Comment by teresarevious-wf** [comment]
@rosie run_merge_script

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Pull request merged**
