### PR TITLE
CP-899 Move System null-check to a useful location

### LINKED ISSUE #93: Invalid check
There's a check in adapter.js at the end for `if(!System){` however it will never come that far since in the first line of the method it would already bomb out: `System.config(` when System is undefined. This should be moved to the top.

### PR DESCRIPTION
**Pull request by maxwellpeterson-wf**
## Issue
Fixes #93 

## Changes
**Source:**
- Move null check of System above first usage
- minor style fixes

**Tests:**
- No change

## Areas of Regression
- None

## Testing
- Ensure karma-jspm still works with another Workiva repository

@trentgrover-wf 
@evanweible-wf 
@dustinlessard-wf 
FYI @jayudey-wf

### CODE REVIEW

**Comment by dustinlessard-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - installed into a project that consumes karma-jspm, ran `gulp dist` and `gulp test` and both completed as expected
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Comment by jayudey-wf** [comment]
@rosie run_merge_script

**Pull request merged**
