### PR TITLE
CP-1765 Move jspm file pattern to end of served files

### PR DESCRIPTION
**Pull request by svi3c**
Relates to #97

### CODE REVIEW

**Comment by evanweible-wf** [comment]
@maxwellpeterson-wf @trentgrover-wf https://github.com/Workiva/karma-jspm/issues/97#issuecomment-217849161

If this worked for @svi3c, I see no reason not to try it.

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for merge and release

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction (derived from discussion with Max Peterson)
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - verified that tasks were still able to be completed with this version of karma-jspm in a project that utilizes karma-jspm
- [ ] Unit test created/updated
- [ ] All unit tests pass 

Merging into master.

**Pull request merged**
