### PR TITLE
CP-838 Release karma-jspm 2.0.1

### PR DESCRIPTION
**Pull request by jayudey-wf**
PRs contained in this release:

https://github.com/Workiva/karma-jspm/pull/81

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/karma-jspm/compare/2.0.1-beta.2...Release_2.0.1

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+10

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Comment by yordis** [comment]
+1
@mackenzieobleness-wf when you are going to update the npm version?

**Comment by maxwellpeterson-wf** [comment]
@yordis Sorry about that, it is published now.

**Comment by yordis** [comment]
@mackenzieobleness-wf  great!

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Pull request merged**
