### PR TITLE
CP-1446 Update gulp-jasmine dependency - fixes #133

### LINKED ISSUE #133: Failed test on Windows due to obsolite gulp-jasmine dependency
Due to the hacky line
```js
// NOTE: this is really janky but a main function will be added in the next 2.x.x release
var jasmineRequire = require('../node_modules/jasmine-core/lib/jasmine-core/jasmine.js');
```
in minijasminenode2, `npm test` fails on Windows.

OS: Windows10
node: v5.7.1
npm: 3.6.0

Error:
```
> karma-jspm@2.0.3 test C:\Users\dotnet\Projects\opensource\karma-jspm
> gulp test

[12:54:43] Using gulpfile ~\Projects\opensource\karma-jspm\gulpfile.js
[12:54:43] Starting 'test'...
[12:54:43] 'test' errored after 27 ms
[12:54:43] Error: Cannot find module '../node_modules/jasmine-core/lib/jasmine-core/jasmine.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\dotnet\Projects\opensource\karma-jspm\node_modules\minijasminenode2\lib\index.js:5:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

### PR DESCRIPTION
**Pull request by dotnetCarpenter**
Update gulp-jasmine dependency

### CODE REVIEW

**Comment by evanweible-wf** [comment]
+1

@maxwellpeterson-wf @trentgrover-wf @dustinlessard-wf

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for merge

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction (derived from discussion with Max Peterson)
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - verified that tasks were still working with this version of karma-jspm installed
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
