### PR TITLE
CP-774 remove .idea folder

### LINKED ISSUE #71: idea folder in npm install
http://take.ms/gWCTi

you probably don't want that.

### PR DESCRIPTION
**Pull request by maxwellpeterson-wf**
## Issue
Fixes #71. This will prevent the .idea directory from showing up in the npm artifact.

## Changes
**Source:**
- None.

**Tests:**
- None.

## Areas of Regression
- None.

## Testing
- CI passes

@trentgrover-wf 
@evanweible-wf 
@dustinlessard-wf 
FYI @jayudey-wf

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
Additionally, everyone should make sure that `.idea` is in your global gitignore. Ideally, each individual project shouldn't have to add things like this to the `.gitignore`.

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
go @rmconsole-wf

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - passing CI
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Comment by teresarevious-wf** [comment]
@rosie run_merge_script

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Comment by teresarevious-wf** [comment]
@rmconsole2-wf

**Comment by farid123good** [comment]
I can't be able to remove .idea files. How to do this?

**Pull request merged**
