### PR TITLE
CP-569 Karma-jspm update License

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
- License is out of date and missing year and copyright owner in one spot

## Changes
**Source:**
- `Workiva LLC` --> `Workiva Inc.`
- `2014` --> `2014-2015`

**Tests:**
- n/a

## Areas of Regression
- none

## Testing
- n/a

## Code Review
@trentgrover-wf
@maxwellpeterson-wf

### CODE REVIEW

**Comment by rmconsole-wf** [comment]
**A compliance requirement has not been met.**
 This pull request should not be merged. See RM Checklist for more info.

## General Information
Ticket(s): None found in title
Code Review: https://github.com/Workiva/karma-jspm/pull/50
CI: 
Automation Run: 

## SOC 1 Checklist
- [ ] All commits reviewed (7bb394e3f43fa029e6f927d66956cbd65e7d64fd)
- [x] QA Review
- [x] Security Review Completed if Applicable:  (N/A)

To remain in SOC1 Compliance the following users cannot merge this PR:
* evanweible-wf

## RM Checklist
- [ ] Unit Tests Updated
  - [ ] Tests updated for .js code changes

## Additional Information

		When this pull is merged I will not be able to function
		properly because no ticket is included in the title.
		If your team has decided not to use jira please indicate this in rmconsole

***
*Last updated on Monday, April 27 02:34 PM CST*

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
go @rmconsole-wf

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction (n/a, updating licenses)
- [ ] Dev +1's
- [ ] Dev/QA +10 (tests passed)
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
