### PR TITLE
CP-2040 Release karma-jspm 2.2.1

### PR DESCRIPTION
**Pull request by rm-astro-wf**
Pulls Included in Release:
* [Fix "Error" when using jspm v0.17.0-beta.35](https://github.com/Workiva/karma-jspm/pull/183)
* [CP-2409 Update glob dependency](https://github.com/Workiva/karma-jspm/pull/173)

Requested by: @charliekump-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/karma-jspm/compare/2.2.0...version-bump-karma-jspm-2-2-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/karma-jspm/compare/2.2.0...2.2.1

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by charliekump-wf** [comment]
QA +1

- [x] Dev +1 only needed for release.

@Workiva/release-management-p for merge into master

**Pull request merged**
